
num1 = int(input("input a number: "))
num2 = int(input("input a number "))
num3 = int(input("input a number "))
num4 = int(input("input a number "))

print(num1 / num2)
print(num1 // num3)
print(num1 % num4)
print(num2 // num4)
print(num4 % num3)
print(num1 // num4)
print(num3 // num2)
print(num4 % num2)
print(num3 // num3)
print(num1 / num3)